export { default as HomeScreen } from './HomeScreen';
export { default as LoginScreen } from './LoginScreen';
export { default as RegisterScreen } from './RegisterScreen';
export { default as ForgotPasswordScreen } from './ForgotPasswordScreen';
export { default as Dashboard } from './Dashboard';
export { default as Test } from './Test';
export { default as BoardList } from './BoardList';
export { default as DetailBoard } from './DetailBoard';
export { default as Word } from './Word';
